---
output: rmarkdown::github_document
---



```{r libraries, message=FALSE, warning=FALSE, include=FALSE}
library(fontawesome)
```

# Working with Data Workshops

## Course Modules

1. Data Collection
2. Data Management
3. Data Processing and Analysis
4. Telling stories using data
5. Introduction to scripting languages

## Resources

| Session | Topic | Date | Slide Deck | Session Recording | Notes |
| :-----: | :---: | :--: | :--------: | :---------------: | :---: |
| 1 | Data Collection | 16/07/21 | [`r fa(name = "firefox-browser", fill = "steelblue", height = "20px")`](https://civicdatalab.in/Working-with-Data-Workshops/modules/module_1_data_collection/session-1.html) [`r fa(name = "file-pdf", fill = "steelblue", height = "20px")`](https://civicdatalab.in/Working-with-Data-Workshops/modules/module_1_data_collection/session-1.pdf) | [`r fa(name = "youtube", fill = "steelblue", height = "20px")`](https://youtu.be/DwfiBPyxlLM) | [`r fa(name = "file-word", fill = "steelblue", height = "20px")`](https://docs.google.com/document/d/1ZBMfqCvjPmqRQr2cUpVazK81SYK4GFJK3qf3uXxJoOY/edit?usp=sharing) |
| 2 | Web scraping & Data Standards | 26/07/21 | [`r fa(name = "firefox-browser", fill = "steelblue", height = "20px")`](https://civicdatalab.in/Working-with-Data-Workshops/modules/module_1_data_collection/session-2/session-2.html) [`r fa(name = "file-pdf", fill = "steelblue", height = "20px")`](https://civicdatalab.in/Working-with-Data-Workshops/modules/module_1_data_collection/session-2/session-2.pdf) | [`r fa(name = "youtube", fill = "steelblue", height = "20px")`](https://www.youtube.com/watch?v=IaA_qClEFMg) | [`r fa(name = "file-word", fill = "steelblue", height = "20px")`](https://docs.google.com/document/d/1O5AbZhz3rAv9Nyy1BF4GWuvS8-AfR8bzbzU4RzwxTRw/edit) |
| 3 | Data Exploration | 04/08/21 | [`r fa(name = "firefox-browser", fill = "steelblue", height = "20px")`](https://civicdatalab.in/Working-with-Data-Workshops/modules/module_2_data_exploration/session-1.html) [`r fa(name = "file-pdf", fill = "steelblue", height = "20px")`](https://civicdatalab.in/Working-with-Data-Workshops/modules/module_2_data_exploration/session-1.pdf) | [`r fa(name = "youtube", fill = "steelblue", height = "20px")`](https://youtu.be/JRIhWqQNFK8) | [`r fa(name = "file-word", fill = "steelblue", height = "20px")`](https://docs.google.com/document/d/1nSnAOq1Uyr4oaGFe_K-8nr7PFTmYAr4Zb1iizxjtU6k/edit) |
| 4 | Working with databases | 12/08/21 | [`r fa(name = "firefox-browser", fill = "steelblue", height = "20px")`](https://civicdatalab.in/Working-with-Data-Workshops/modules/module_2_data_exploration/session-2.html) [`r fa(name = "file-pdf", fill = "steelblue", height = "20px")`](https://civicdatalab.in/Working-with-Data-Workshops/modules/module_2_data_exploration/session-2.pdf) | [`r fa(name = "youtube", fill = "steelblue", height = "20px")`](https://youtu.be/jKNImiPHII0) | [`r fa(name = "file-word", fill = "steelblue", height = "20px")`](https://docs.google.com/document/d/1cbW0gYCYyiCB788foex-pXM7glZ5oeysJ8dQXCqYIRE/edit?usp=sharing) |
| 5 | Working with databases | 26/08/21 | [`r fa(name = "firefox-browser", fill = "steelblue", height = "20px")`](https://civicdatalab.in/Working-with-Data-Workshops/modules/module_2_data_exploration/session-3.html) [`r fa(name = "file-pdf", fill = "steelblue", height = "20px")`](https://civicdatalab.in/Working-with-Data-Workshops/modules/module_2_data_exploration/session-3.pdf) | [`r fa(name = "youtube", fill = "steelblue", height = "20px")`](https://youtu.be/JNTPkhlHbpQ) | [`r fa(name = "file-word", fill = "steelblue", height = "20px")`](https://docs.google.com/document/d/1jCUYT1qGbKd0FA1VAZ65rUbCJirPnV3WSADHT2HEbHw/edit?usp=sharing) |
| 6 | Working with databases | 02/09/21 | [`r fa(name = "firefox-browser", fill = "steelblue", height = "20px")`](https://civicdatalab.in/Working-with-Data-Workshops/modules/module_2_data_exploration/session-4.html) [`r fa(name = "file-pdf", fill = "steelblue", height = "20px")`](https://civicdatalab.in/Working-with-Data-Workshops/modules/module_2_data_exploration/session-4.pdf) | [`r fa(name = "youtube", fill = "steelblue", height = "20px")`](https://youtu.be/dg9vspdxZUA) | [`r fa(name = "file-word", fill = "steelblue", height = "20px")`]() |
| 7 | Data Analysis - Use Cases | 09/09/21 | [`r fa(name = "firefox-browser", fill = "steelblue", height = "20px")`](https://civicdatalab.in/Working-with-Data-Workshops/modules/module_3_data_analysis/session-1/session-1.html) [`r fa(name = "file-pdf", fill = "steelblue", height = "20px")`](https://civicdatalab.in/Working-with-Data-Workshops/modules/module_3_data_analysis/session-1/session-1.pdf) | [`r fa(name = "youtube", fill = "steelblue", height = "20px")`](https://youtu.be/TanPhQhdMuI) | [`r fa(name = "file-word", fill = "steelblue", height = "20px")`]() |
| 8 | Data Analysis - Analysis Deep Dive | 17/09/21 | [`r fa(name = "firefox-browser", fill = "steelblue", height = "20px")`](https://civicdatalab.in/Working-with-Data-Workshops/modules/module_3_data_analysis/session-2/session-2.html) [`r fa(name = "file-pdf", fill = "steelblue", height = "20px")`](https://civicdatalab.in/Working-with-Data-Workshops/modules/module_3_data_analysis/session-2/session-2.pdf) | [`r fa(name = "youtube", fill = "steelblue", height = "20px")`](https://youtu.be/8kp5CxqwYK8) | [`r fa(name = "file-word", fill = "steelblue", height = "20px")`]() |
| 9 | Data Analysis - UWAZI & GIS Analysis | 29/09/21 | [`r fa(name = "firefox-browser", fill = "steelblue", height = "20px")`](https://docs.google.com/presentation/d/16-2zyEQI_Mn93LZ7iTcVKMG40POPGw_RThNwCsQNqls/edit?usp=sharing) [`r fa(name = "file-pdf", fill = "steelblue", height = "20px")`](https://civicdatalab.in/Working-with-Data-Workshops/modules/module_3_data_analysis/session-3/session-3.pdf) | [`r fa(name = "youtube", fill = "steelblue", height = "20px")`](https://youtu.be/zBuAJmWByJM) | [`r fa(name = "file-word", fill = "steelblue", height = "20px")`]() |
| 10 | Data Visualisation | 12/10/21 | [`r fa(name = "firefox-browser", fill = "steelblue", height = "20px")`](https://civicdatalab.in/Working-with-Data-Workshops/modules/module_4_data_viz/session-1/session-1.html) [`r fa(name = "file-pdf", fill = "steelblue", height = "20px")`](https://civicdatalab.in/Working-with-Data-Workshops/modules/module_4_data_viz/session-1/session-1.pdf) | [`r fa(name = "youtube", fill = "steelblue", height = "20px")`](https://youtu.be/qieuVFrFxRo) | [`r fa(name = "file-word", fill = "steelblue", height = "20px")`]() |
| 11 | Data Visualisation - Tools and Resources | 21/10/21 | [`r fa(name = "firefox-browser", fill = "steelblue", height = "20px")`](https://civicdatalab.in/Working-with-Data-Workshops/modules/module_4_data_viz/session-2/session-2.html) [`r fa(name = "file-pdf", fill = "steelblue", height = "20px")`](https://civicdatalab.in/Working-with-Data-Workshops/modules/module_4_data_viz/session-2/session-2.pdf) | [`r fa(name = "youtube", fill = "steelblue", height = "20px")`](https://youtu.be/cV_OdMY0XXU) | [`r fa(name = "file-word", fill = "steelblue", height = "20px")`]() |
| 12 | Qualitative Data Analysis & Publishing Open Data | 28/10/21 | [`r fa(name = "firefox-browser", fill = "steelblue", height = "20px")`](https://civicdatalab.in/Working-with-Data-Workshops/modules/module_5_qualitative_data_analysis/session-1/session-1.html) [`r fa(name = "file-pdf", fill = "steelblue", height = "20px")`](https://civicdatalab.in/Working-with-Data-Workshops/modules/module_5_qualitative_data_analysis/session-1/session-1.pdf) | [`r fa(name = "youtube", fill = "steelblue", height = "20px")`](https://youtu.be/zIs-e1m26R4) | [`r fa(name = "file-word", fill = "steelblue", height = "20px")`]() |


_Note: The keyboard shortcuts for the HTML version of the slide deck can be viewed by pressing the `h` key_

## Moderators

1. [Apoorv Anand](mailto:apoorv@civicdatalab.in)
2. [Samriddhi](mailto:samriddhi@civicdatalab.in)

## Links

- [Discussion Forum](https://chat.civicdatalab.in/group/vidhi-data-workshops)
- [Google Drive](https://drive.google.com/drive/folders/1RFCQ19wUuMB5QRTpbEndCjHu_zQ8Rx6y?usp=sharing)
